apiVersion: v1
kind: Service
metadata:
  name: minikube-price-generator
  labels:
    app: minikube-price-generator
spec:
  type: NodePort
  ports:
    - port: 1111
      protocol: TCP
      targetPort: 1111
  selector:
    app: minikube-price-generator